---
  - name: Detect init system
    shell: |
      if [[ `/sbin/init --version 2> /dev/null` =~ upstart ]]; then echo upstart;
      elif [[ `systemctl` =~ -\.mount ]]; then echo systemd;
      elif [[ -f /etc/init.d/cron && ! -h /etc/init.d/cron ]]; then echo sysv-init;
      elif [[ -f /sbin/openrc-run ]]; then echo openrc;
      else echo UNKNOWN;
      fi
    become: yes
    args:
      executable: /bin/bash
    register: init_detect_raw

  - set_fact:
      init_system: "{{ init_detect_raw.stdout }}"

  - debug: msg="Detected system to come with '{{ init_detect_raw.stdout }}'"

