---
  - name: Check /proc/1/exe
    shell: readlink /proc/1/exe
    become: yes
    args:
      executable: /bin/sh
    register: proc1exe

  - debug:
      msg: "/proc/1/exe points to '{{ proc1exe.stdout }}'"

  - name: Detect init system
    shell: | 
      init=`readlink /proc/1/exe`;
      if [[ `/sbin/init --version 2> /dev/null` =~ upstart ]]; then echo upstart;
      elif [[ `systemctl` =~ -\.mount ]]; then echo systemd;
      elif [[ "$init" == "/sbin/init" ]]; then echo sysv-init;
      elif [[ -f /sbin/openrc-run ]]; then echo openrc;
      else echo UNKNOWN;
      fi
    become: yes
    args:
      executable: /bin/bash
    register: init_detect_raw

  - set_fact:
      init_system: "{{ init_detect_raw.stdout }}"

  - debug: msg="Detected system to come with '{{ init_detect_raw.stdout }}'"

# readlink /proc/1/exe