---
  - name: Check /proc/1/exe
    shell: readlink /proc/1/exe
    become: yes
    args:
      executable: /bin/sh
    register: proc1exe

  - debug:
      msg: "/proc/1/exe points to '{{ proc1exe.stdout }}'"

  - name: Detect init system
    shell: | 
      init=`readlink /proc/1/exe`;
      if   [ "$init" = "/lib/systemd/systemd" ]]; then echo systemd;
      elif [ "$init" = "/usr/lib/systemd/systemd" ]]; then echo systemd;
      elif [ "$init" = "/sbin/init" ]; then echo sysv-init;
      elif [ "$init" = "/bin/busybox" ]; then echo openrc;
      else echo UNKNOWN;
      fi
    become: yes
    args:
      executable: /bin/sh
    register: init_detect_raw

  - set_fact:
      init_system: "{{ init_detect_raw.stdout }}"

  - debug: msg="Detected system to come with '{{ init_detect_raw.stdout }}'"

# readlink /proc/1/exe