
FROM fedora:27

# Install Ansible
RUN dnf -y update && \
    dnf install -y python2 python2-dnf libselinux-python procps-ng && \
    dnf -y install ansible && \
    mkdir -p /etc/ansible

# Install Ansible inventory file
RUN echo "[local]" > /etc/ansible/hosts && \
    echo "localhost ansible_connection=local" >> /etc/ansible/hosts
