FROM alpine:3.6

ENV container docker

RUN apk --update add openrc python py-pip openssl ca-certificates tar make gcc musl-dev && \
    apk --update add --virtual build-dependencies python-dev libffi-dev \
        openssl-dev build-base && \
    pip install -U pip && \
    pip install -U cffi ansible && \
    apk del build-dependencies && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /etc/ansible

# Install Ansible inventory file
RUN echo "[local]" > /etc/ansible/hosts && \
    echo "localhost ansible_connection=local" >> /etc/ansible/hosts

